### ISSUE TITLE
Minor things needed for submission

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/data_versioning#14]
- [x] Abstract (WC)
- [x] Keywords
- [x] Import Figures #10 (WC)
- [x] Try new figure #11 (DF)
- [x] Discussion (limited). General probelm. An example of solution. Key features (WC, DF)
- [x] MP comments, needs clearer exposition of how this would work. Currently have lists of benefits, but no overview  (MP)
- [x] Concise description of what datastorr does (MP)
- [x] Title for paper #13
- [x] Better name for concept #12 
- [x] More citations of prior work
- [x] One more review of tables (DF)

**Comment by wcornwell** [comment]
Should probably mention and discuss this as a likely future development.  Git for data: https://clusterhq.com/2016/11/03/flockerhub-fli-release/
